### PR TITLE
L1 profile update issue fixes

### LINKED ISSUE #31: TvSettings:  L1 Issues found 1.3.0
Fixing issues found during 1.3.0 test 
(addressing Issue #24 as well in this ticket.)
Bank 6:
- Issue in L1  reading color temperature data from profile
- The color temperature RGB gain test cases range is from 0 to 2047. VTS handles only values from 1 to 2047. Correction is required.

Bank 7:
- In the test_l1_tvSettings_positive_GetColorTemp_Ggain_onSource test case, the variable is incorrectly compared.
- For all component color test cases, tvDataColor_NONE is not a valid parameter. Correction is required in the YAML file.
- The size of the Gamma Table is incorrectly specified. Correction is required.
- In SaveGammaTable, for the positive test case, the error code is wrongly compared with "Invalid param."
- In test_l1_tvSettings_negative_GetDefaultGammaTable, the color temperature index value is incorrectly assigned and parsed.

Test suite name correction required for test_l1_tvSettings_positive_GetPQParams

### PR DESCRIPTION
**Pull request by akhilbhas**
* Fixing array out of bound issues
* Changing indexing logic
Closes #31

### CODE REVIEW

File: src/test_l1_tvSettings.c [hunk 1]
```diff
@@ -12580,7 +12580,7 @@ void test_l1_tvSettings_negative_GetDefaultGammaTable (void)
         platformFlag = false;
         for (unsigned int j = 0; j < colorTempCount ; j++ )
         {
-            snprintf(keyValue, UT_KVP_MAX_ELEMENT_SIZE, "tvSettings/ColorTemperature/index/%d", i);
+            snprintf(keyValue, UT_KVP_MAX_ELEMENT_SIZE, "tvSettings/ColorTemperature/index/%d", j);
             colorTempValue = (tvColorTemp_t) UT_KVP_PROFILE_GET_UINT32(keyValue);
             if(colorTempValue == (tvColorTemp_t)i)
             {
```
Comment (Anbukannadhasan) [inline src/test_l1_tvSettings.c:12586]: In line number 12593, are we supposed to pass the index i instead of colorTempValue? This is because we intend to pass the unsupported color temp enum value.

File: src/test_l1_tvSettings.c [hunk 2]
```diff
@@ -12015,10 +12016,10 @@ void test_l1_tvSettings_negative_GetColorTemp_B_post_offset_onSource (void)
     for (unsigned int i = 0; i < tvColorTemp_MAX; i++)
     {
         platformFlag = false;
-        snprintf(keyValue, UT_KVP_MAX_ELEMENT_SIZE, "tvSettings/ColorTemperature/index/%d", i);
-        colorTempValue = (tvColorTemp_t) UT_KVP_PROFILE_GET_UINT32(keyValue);
         for (unsigned int j = 0; j < colorTempCount ; j++ )
         {
+            snprintf(keyValue, UT_KVP_MAX_ELEMENT_SIZE, "tvSettings/ColorTemperature/index/%d", j);
+            colorTempValue = (tvColorTemp_t) UT_KVP_PROFILE_GET_UINT32(keyValue);
             if(colorTempValue == (tvColorTemp_t)i)
```
Comment (Anbukannadhasan) [inline src/test_l1_tvSettings.c:12023]: "In line number 12032, are we supposed to pass the index i instead of colorTempValue? This is because we intend to pass the unsupported enum value."

File: src/test_l1_tvSettings.c [hunk 3]
```diff
@@ -11605,7 +11606,7 @@ void test_l1_tvSettings_negative_GetColorTemp_G_post_offset_onSource (void)
         platformFlag = false;
         for (unsigned int j = 0; j < colorTempCount ; j++ )
         {
-            snprintf(keyValue, UT_KVP_MAX_ELEMENT_SIZE, "tvSettings/ColorTemperature/index/%d", i);
+            snprintf(keyValue, UT_KVP_MAX_ELEMENT_SIZE, "tvSettings/ColorTemperature/index/%d", j);
             colorTempValue = (tvColorTemp_t) UT_KVP_PROFILE_GET_UINT32(keyValue);
             if(colorTempValue == (tvColorTemp_t)i)
```
Comment (Anbukannadhasan) [inline src/test_l1_tvSettings.c:11611]: "In line number 11619, are we supposed to pass the index i instead of colorTempValue? This is because we intend to pass the unsupported value."

File: src/test_l1_tvSettings.c [hunk 4]
```diff
@@ -11196,7 +11197,7 @@ void test_l1_tvSettings_negative_GetColorTemp_R_post_offset_onSource (void)
...
             {
```
Comment (Anbukannadhasan) [inline src/test_l1_tvSettings.c:11203]: "In line number 11210, are we supposed to pass the index i instead of colorTempValue? This is because we intend to pass the unsupported value."

File: src/test_l1_tvSettings.c [hunk 5]
```diff
@@ -10783,7 +10784,7 @@ void test_l1_tvSettings_negative_GetColorTemp_Bgain_onSource (void)
...
```
Comment (Anbukannadhasan) [inline src/test_l1_tvSettings.c:10790]: "In line number 10797, are we supposed to pass the index i instead of colorTempValue? This is because we intend to pass the unsupported value."

File: src/test_l1_tvSettings.c [hunk 6]
```diff
@@ -9968,9 +9969,9 @@ void test_l1_tvSettings_negative_GetColorTemp_Rgain_onSource (void)
...
     {
         platformFlag = false;
-        for (unsigned int j = 0; j < colorTempCount ; j++ )
+        for (unsigned int j = 0; j < colorTempCount; j++ )
         {
-            snprintf(keyValue, UT_KVP_MAX_ELEMENT_SIZE, "tvSettings/ColorTemperature/index/%d", i);
+            snprintf(keyValue, UT_KVP_MAX_ELEMENT_SIZE, "tvSettings/ColorTemperature/index/%d", j);
             colorTempValue = (tvColorTemp_t) UT_KVP_PROFILE_GET_UINT32(keyValue);
             if(colorTempValue == (tvColorTemp_t)i)
             {
```
Comment (Anbukannadhasan) [inline src/test_l1_tvSettings.c:9977]: "In line number 9984, are we supposed to pass the index i instead of colorTempValue? This is because we intend to pass the unsupported value."

**Review by Anbukannadhasan — COMMENTED** [review]
In some of the negative cases, when validating unsupported enum data, the logic was intended to find the indexes of unsupported enums but incorrectly passed supported values instead. The team that implemented this mishandled several functions. I had already corrected these in our previous releases and merged them into Develop. However, I still see a few issues and have added review comments. Could you please review those areas again throughout the code?

File: src/test_l1_tvSettings.c (hunk 6 above)
Comment (akhilbhas) [reply src/test_l1_tvSettings.c:9977]: updated

File: src/test_l1_tvSettings.c (hunk 5 above)
Comment (akhilbhas) [reply src/test_l1_tvSettings.c:10790]: updated

File: src/test_l1_tvSettings.c (hunk 4 above)
Comment (akhilbhas) [reply src/test_l1_tvSettings.c:11203]: updated

File: src/test_l1_tvSettings.c (hunk 3 above)
Comment (akhilbhas) [reply src/test_l1_tvSettings.c:11611]: updated

File: src/test_l1_tvSettings.c (hunk 2 above)
Comment (akhilbhas) [reply src/test_l1_tvSettings.c:12023]: updated

File: src/test_l1_tvSettings.c (hunk 1 above)
Comment (akhilbhas) [reply src/test_l1_tvSettings.c:12586]: updated

**Review by Anbukannadhasan — APPROVED** [review]
Approved
