### PR TITLE
gh #128 updated SetAndGetColorTemp gain & post offset L2 test cases

### LINKED ISSUE #128: L2 SetAndGetColorTemp Gain & Post Offset tests failing
The following L2 testcases are failing:
SetAndGetColorTempRgain
SetAndGetColorTempGgain
SetAndGetColorTempBgain
SetAndGetColorTempRpostoffset
SetAndGetColorTempGpostoffset
SetAndGetColorTempBpostoffset

### PR DESCRIPTION
**Pull request by ranburen**
Updated the following testcases since gain and offset values were compared with wrong expected value:
SetAndGetColorTempRgain
SetAndGetColorTempGgain
SetAndGetColorTempBgain
SetAndGetColorTempRpostoffset
SetAndGetColorTempGpostoffset
SetAndGetColorTempBpostoffset

### CODE REVIEW

**Review by utkarshece14 — APPROVED** [review]
LGTM

File: src/test_l2_tvSettings.c [hunk 1]
```diff
@@ -2035,10 +2035,11 @@ void test_l2_tvSettings_SetAndGetColorTempRgain(void)
 
             UT_LOG_DEBUG("Retrieved rgain: %d", rgain);
             // Ensure the saved value with 2047 doesn't impact the set value 1024
-            UT_ASSERT_EQUAL(rgain, setRgain);
-            if (rgain != setRgain)
+            UT_ASSERT_NOT_EQUAL(rgain, setRgain);
```
Comment (Anbukannadhasan) [inline src/test_l2_tvSettings.c:2038]: In the first loop at line 1981, the saveOnly flag is set to 0, and a Get check is performed immediately after the Set call. With the latest HAL behavior, saveOnly=0 updates the HW only, while the Get API fetches the value from the DB.

As a result, the value retrieved by Get may not match the value just set, leading to a mismatch failure and causing the test case to fail.

Recommendation:
Use saveOnly=1 in the loop instead.
saveOnly=1 writes the value to the DB, and Get will correctly return the same value.

This approach is applicable to all gain and offset test cases to ensure that Set and Get validation passes.

**Review by Anbukannadhasan — COMMENTED** [review]
Added review comment

File: src/test_l2_tvSettings.c (hunk 1 above)
Comment (ranburen) [reply src/test_l2_tvSettings.c:2038]: Thanks for the comment. As per the API documentation, saveOnly=0 will both save the value to DB and apply it immediately to hardware. saveOnly=1 will save the value in DB only (not applied to hardware immediately).

Therefore, a subsequent Get after Set with either saveOnly=0 or saveOnly=1 should still return the same value, since the DB is updated in both cases.

**Review by Anbukannadhasan — APPROVED** [review]
Approved
